return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "stylua",
      "shfmt",
      "black",
      "clojure-lsp",
      "csharp-language-server",
      "dockerfile-language-server",
      "emmet-language-server",
      "eslint-lsp",
      "golines",
      "gopls",
      "isort",
      "json-lsp",
      "lua-language-server",
      "marksman",
      "prettier",
      "pyright",
      "rust-analyzer",
      "selene",
      "shfmt",
      "sql-formatter",
      "stylua",
      "typescript-language-server",
      "xmlformatter",
      "yaml-language-server",
      "yamlfmt",
      "yamllint",
      "ruff",
    },
  },
}
